import React,{useState} from "react";
import {createRoot} from "react-dom/client";
import {LayoutDashboard,GitPullRequest,BookOpen,ShieldCheck,BarChart3,Settings,Search,Send,ChevronDown,CheckCircle2,AlertTriangle,Clock3,Code2,Database,MessageSquare,Menu,X,Copy,ThumbsUp,ThumbsDown} from "lucide-react";
import "./styles.css";

const nav=[["Overview",LayoutDashboard],["PR Review",GitPullRequest],["Knowledge",BookOpen],["Security",ShieldCheck],["Evaluations",BarChart3],["Settings",Settings]];
const prs=[
 {id:"#482",title:"Refactor authentication middleware",repo:"atlas-api",author:"Maya Chen",status:"Review ready",risk:"Low",time:"18 min ago"},
 {id:"#479",title:"Add invoice export endpoint",repo:"billing-service",author:"Omar Khan",status:"Needs attention",risk:"Medium",time:"1 hr ago"},
 {id:"#476",title:"Cache repository permissions",repo:"platform-core",author:"Sara Lee",status:"Approved",risk:"Low",time:"3 hrs ago"}
];
function App(){
 const [page,setPage]=useState("Overview"),[open,setOpen]=useState(false),[query,setQuery]=useState(""),[answer,setAnswer]=useState("");
 const ask=()=>{if(!query.trim())return;setAnswer("Based on the indexed engineering guidance, prefer a single permission boundary around repository access, validate organization membership before every protected operation, and avoid returning raw secrets to clients. The relevant policy is cited from Security Playbook §4.2 and Repository Access Standard §2.1.");};
 return <div className="shell">
  <header className="topbar"><div className="brand"><div className="logo"><Code2 size={21}/></div><div><b>CodeAtlas</b><span>Engineering intelligence</span></div></div>
   <button className="menuBtn" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button>
   <nav className={open?"nav open":"nav"}>{nav.map(([n,I])=><button className={page===n?"active":""} onClick={()=>{setPage(n);setOpen(false)}} key={n}><I size={17}/>{n}</button>)}</nav>
   <div className="topActions"><div className="org"><span className="dot"/> Acme Labs <ChevronDown size={15}/></div><div className="avatar">EA</div></div>
  </header>
  <main>
   {page==="Overview"&&<><section className="hero"><div><p className="eyebrow">ENGINEERING CONTROL CENTER</p><h1>Ship better code,<br/><em>with context.</em></h1><p className="sub">Search trusted engineering knowledge, review pull requests, and keep every AI answer grounded in your approved sources.</p></div><div className="pulse"><div className="ring"><ShieldCheck/></div><b>Protected workspace</b><span>Repository access is scoped</span></div></section>
   <section className="stats">{[["Indexed sources","148","↑ 12 this week",Database],["Open reviews","07","2 need attention",GitPullRequest],["Security checks","99.2%","policy coverage",ShieldCheck],["AI responses","2,481","97.4% grounded",MessageSquare]].map(([a,b,c,I])=><div className="stat" key={a}><I/><span>{a}</span><strong>{b}</strong><small>{c}</small></div>)}</section>
   <div className="grid"><section className="card"><div className="cardHead"><div><h2>Ask engineering</h2><p>Answers use indexed, approved sources.</p></div><span className="live">● STREAMING</span></div><div className="askbox"><textarea value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ask about architecture, APIs, testing, conventions..."/><button onClick={ask}><Send size={17}/> Ask</button></div>{answer&&<div className="answer"><div className="answerTitle"><span className="ai">AI</span><b>Grounded answer</b></div><p>{answer}</p><div className="citations"><span>§ Security Playbook 4.2</span><span>§ Repository Access Standard 2.1</span></div><div className="feedback"><button><ThumbsUp size={15}/></button><button><ThumbsDown size={15}/></button><span>Was this useful?</span></div></div>}</section>
   <section className="card"><div className="cardHead"><div><h2>Recent pull requests</h2><p>Automated checks and review signals.</p></div><button className="textBtn" onClick={()=>setPage("PR Review")}>View all</button></div><div className="prlist">{prs.map(p=><div className="pr" key={p.id}><div className="prIcon"><GitPullRequest size={18}/></div><div className="prMain"><b>{p.id} · {p.title}</b><span>{p.repo} · {p.author} · {p.time}</span></div><span className={"badge "+p.risk.toLowerCase()}>{p.risk}</span></div>)}</div></section></div></>}
   {page==="PR Review"&&<Page title="Pull-request review" icon={GitPullRequest}><div className="reviewLayout"><div className="card"><div className="cardHead"><div><h2>#482 Refactor authentication middleware</h2><p>atlas-api · 14 files changed · 186 additions · 74 deletions</p></div><span className="badge low">LOW RISK</span></div><div className="checks">{["Repository access scoped","No exposed secrets","Style rules passed","Suggested tests ready"].map((x,i)=><div><CheckCircle2/><span>{x}</span><small>{i===3?"4 suggestions":"Passed"}</small></div>)}</div><div className="diff"><div className="diffbar">src/auth/middleware.ts <span>+18 −7</span></div><pre><code><i>@@ verifySession(req, res, next)</i>{"\n"}<span className="minus">- const token = req.headers.authorization;</span>{"\n"}<span className="plus">+ const token = getBearerToken(req);</span>{"\n"}<span className="plus">+ if (!token) return res.status(401).end();</span>{"\n"}{"  const session = await auth.verify(token);"}{"\n"}{"  if (!session) return res.status(401).end();"}{"\n"}{"  req.user = session.user;"}</code></pre></div></div><aside className="card sidecard"><h3>Review summary</h3><div className="score">A<span>92</span></div><p>Clean change with strong boundary validation. One test for expired bearer tokens is recommended.</p><hr/><b>Suggested tests</b><ul><li>Expired token → 401</li><li>Missing header → 401</li><li>Cross-org token → 403</li></ul></aside></div></Page>}
   {page==="Knowledge"&&<Page title="Engineering knowledge" icon={BookOpen}><div className="searchLarge"><Search/><input placeholder="Search documentation, snippets, runbooks..." defaultValue="repository access"/></div><div className="knowledgeGrid">{["Repository Access Standard","API Error Handling Guide","Testing Playbook","Frontend Architecture","Security Playbook","Node.js Service Conventions"].map((x,i)=><div className="source"><div className="sourceIcon"><BookOpen/></div><div><b>{x}</b><p>{["Access boundaries, organization isolation and permission checks.","Consistent errors, status codes and response envelopes.","Unit, integration and end-to-end testing patterns.","Component boundaries and state management conventions.","Secrets, tokens and secure model usage policies.","Service layout, logging and dependency conventions."][i]}</p><span>Verified source · {12+i*7} sections</span></div></div>)}</div></Page>}
   {page==="Security"&&<Page title="Security & access" icon={ShieldCheck}><div className="securityGrid">{[["Secret scanning","All indexed content scanned before processing","Protected"],["Organization isolation","Data and retrieval scopes separated by org","Enforced"],["Repository permissions","Access follows connected repository permissions","Enforced"],["Model usage logging","Prompts, tools and response metadata retained","Enabled"]].map(x=><div className="card security"><ShieldCheck/><div><h3>{x[0]}</h3><p>{x[1]}</p><span className="secure">{x[2]}</span></div></div>)}</div></Page>}
   {page==="Evaluations"&&<Page title="Evaluation center" icon={BarChart3}><div className="evalTop"><div className="card bigMetric"><span>Grounded answer accuracy</span><strong>94.7%</strong><small>+3.8% vs previous run</small></div><div className="card bigMetric"><span>Code review agreement</span><strong>91.2%</strong><small>1,240 reviewed examples</small></div><div className="card bigMetric"><span>Safety pass rate</span><strong>99.6%</strong><small>0 critical failures</small></div></div><div className="card"><h2>Evaluation datasets</h2><div className="table">{["Engineering QA v3","PR Review Gold Set","Secret Safety Suite","Citation Accuracy"].map((x,i)=><div className="tr"><b>{x}</b><span>{[1280,640,420,920][i]} examples</span><strong>{[94.7,91.2,99.6,96.1][i]}%</strong><button className="textBtn">Open</button></div>)}</div></div></Page>}
   {page==="Settings"&&<Page title="Workspace settings" icon={Settings}><div className="settings card">{["AI response citations","Human feedback collection","Model usage audit log","Repository permission sync","Automatic secret scanning"].map((x,i)=><div><div><b>{x}</b><p>{["Require source references in engineering answers.","Allow reviewers to rate and annotate responses.","Record model, tool and token metadata.","Refresh access scopes from connected repositories.","Block secrets before indexing or model retrieval."][i]}</p></div><label className="switch"><input type="checkbox" defaultChecked/><span/></label></div>)}</div></Page>}
  </main></div>
}
function Page({title,icon:I,children}){return <><section className="pageTitle"><div className="miniIcon"><I/></div><div><p className="eyebrow">CODEATLAS</p><h1>{title}</h1></div></section>{children}</>}
createRoot(document.getElementById("root")).render(<App/>);